apiVersion: "v1"
kind: Pod
metadata:
  name: web-devops
  labels:
    name: devops
    env: dev
spec:
  containers:
    - name: devopsweb
      image: "https://hub.docker.com/repository/docker/arvindvijaya/hellodevopsdocker"
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
