apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: rs-devops
  labels:
    name: devops
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      name: devops
  template:
    metadata:
      labels:
        name: devops
        env: dev
    spec:
        containers:
          - name: devopsweb
            image: arvindvijaya/hellodevopsdocker:latest
            ports:
                - containerPort: 8000
                  name: http
                  protocol: TCP
        imagePullSecrets:
          - name: arvind-secret-key
