apiVersion: "v1"
kind: Pod
metadata:
  name: web-devops
  labels:
    name: devops
    env: dev
spec:
  containers:
    - name: devopsweb
      image: arvindvijaya/hellodevopsdocker:v1
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
  imagePullSecrets:
    - name: arvind-secret-key
