apiVersion:"v1"
kind: ReplicaSet
metadata:
  name: devops-replicaset
  labels:
    name: devops
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      name: devops
  template:
    metadata:
      labels:
        name: devops
        env: dev
    spec:
      containers:
         - name: devopsweb
           image: "https://hub.docker.com/repository/docker/arvindvijaya/hellodevopsdocker"
           ports:
              - containerPort: 1020
                name: http
                protocol: TCP